import os
import json
from dataclasses import asdict
from .config_loader import ReportConfig
from .data_transformer import ProjectReport
from .claude_code import invoke_claude_code


def generate_report(report: ProjectReport, config: ReportConfig) -> str:
    output_dir = os.path.abspath(config.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    # Write the data file for Claude Code to consume
    data_path = os.path.join(output_dir, "report-data.json")
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(asdict(report), f, indent=2)

    output_file = config.filename

    # Compose the prompt
    prompt = f"""
You are a report generation expert. Your task is to create a single-file,
interactive HTML report from the project data provided.

## Input Data

The file `report-data.json` in the current directory contains the full
project report data. Read it and use it to generate the report.

## Report Requirements

### Structure
1. **Header**: Report title ("{report.title}"), generation timestamp,
   and a prominent overall progress bar showing {report.summary.overall_progress_percent}% completion.

2. **Executive Summary Cards**: Show total work items, total tasks,
   completed/in-progress/pending counts as metric cards with icons.

3. **Phase Progress Section**: For each phase, display:
   - Phase name with its configured color as accent
   - Phase-level progress bar with percentage
   - Expandable/collapsible list of work items in that phase

4. **Work Item Detail** (inside each phase): For each work item show:
   - Work item ID and title
   - **Completion percentage badge** (e.g. "75%") prominently next to the title,
     derived from `progress_percent` in the data (completed tasks / total tasks × 100).
     Color-code it: green >= 80%, orange 40-79%, red < 40%. Show "N/A" when total_tasks = 0.
   - Individual progress bar (completed tasks / total tasks) with the exact percentage label
   - Task counts inline: e.g. "5 / 8 tasks completed"
   - Task breakdown table: Task ID, Title, State (with color-coded badges), Assigned To
   - Visual indicator: green = completed, blue = in progress, gray = pending

5. **Uncategorized Section**: If any work items don't match a configured phase tag,
   list them in a separate "Uncategorized" section.

6. **Project Summary Footer**:
   - Bar chart or horizontal stacked bars showing progress per phase
   - Overall project health indicator

### Technical Requirements
- **Single HTML file** — all CSS and JS inline (no external dependencies)
- Use modern CSS (grid, flexbox, custom properties) for layout
- Responsive design (works on mobile and desktop)
- Collapsible sections using `<details>`/`<summary>` or vanilla JS
- Smooth CSS transitions on progress bars
- Print-friendly styles via `@media print`
- Use the phase colors from the data for theming
- Include a "Generated by {report.generated_by}" footer with timestamp
- Light/dark mode toggle (optional, nice-to-have)

### Chart Rendering
For any charts, use inline SVG generated from the data — do NOT rely on
external chart libraries. Keep it dependency-free.

## Output
Write the complete HTML file to `./{output_file}`.
Do NOT create any other files. Everything must be in the single HTML file.
"""

    print("Invoking Claude Code to generate the HTML report...")
    result = invoke_claude_code(
        prompt=prompt,
        working_dir=output_dir,
        max_turns=15,
    )

    print(f"[Claude Code output] {result[:500]}")

    report_path = os.path.join(output_dir, output_file)
    if not os.path.exists(report_path):
        print(f"Claude Code did not produce the expected file: {report_path}")
        print(f"Raw report data saved at: {data_path} — you can use it manually.")
        raise FileNotFoundError(
            f"Claude Code did not produce the expected file: {report_path}"
        )

    # Clean up the data file after successful generation
    if os.path.exists(data_path):
        os.remove(data_path)

    return report_path
